// Generated by tools/extract_gd_data.py from the Godot scripts. Do not edit by hand.
import type { ChalkDef } from "../game/types";

export const CHALK_DEFS: Record<string, ChalkDef> = {
  "blue_chalk": {
    "name": "Blue Chalk",
    "text": "Next shot gets a longer aim preview and shows two extra contact reads.",
    "shots": 1
  },
  "red_chalk": {
    "name": "Red Chalk",
    "text": "Next shot has +18% force.",
    "shots": 1
  },
  "safe_chalk": {
    "name": "Safe Chalk",
    "text": "Prevents the next scratch marker loss.",
    "shots": 1
  },
  "gold_chalk": {
    "name": "Gold Chalk",
    "text": "Next successful pot grants +$4.",
    "shots": 1
  },
  "bomb_chalk": {
    "name": "Bomb Chalk",
    "text": "First potted ball on the next shot detonates.",
    "shots": 1
  },
  "rail_chalk": {
    "name": "Rail Chalk",
    "text": "First rail hit on the next shot preserves extra speed.",
    "shots": 1
  }
};
