// Generated by tools/extract_gd_data.py from the Godot scripts. Do not edit by hand.
import type { RelicDef } from "../game/types";

export const RELIC_DEFS: Record<string, RelicDef> = {
  "money_ball": {
    "name": "Midas Eye",
    "rarity": "common",
    "family": [
      "Offering",
      "Economy"
    ],
    "text": "Each table starts with one extra gold ball, a bright tithe for the house."
  },
  "sniper": {
    "name": "Dead Man's Sight",
    "rarity": "common",
    "family": [
      "Omen",
      "Aim"
    ],
    "text": "For your first 3 shots each table, the preview line reaches maximum length."
  },
  "entropy_scanner": {
    "name": "Oracle Prism",
    "rarity": "rare",
    "family": [
      "Omen",
      "Ricochet"
    ],
    "text": "For your first 3 shots each table, previews show extra ricochet continuations."
  },
  "center_cut": {
    "name": "Saint's Needle",
    "rarity": "common",
    "family": [
      "Rite",
      "Precision"
    ],
    "text": "Perfect pots add Reputation and $1 Bankroll."
  },
  "rail_coupon": {
    "name": "Rail Tithe",
    "rarity": "common",
    "family": [
      "Oath",
      "Bank"
    ],
    "text": "Bank or kick pots pay Bankroll."
  },
  "combo_receipt": {
    "name": "Twin-Tongue Ledger",
    "rarity": "uncommon",
    "family": [
      "Offering",
      "Multi-pot"
    ],
    "text": "Multi-pot shots add Reputation and Bankroll."
  },
  "spare_ball": {
    "name": "Bone Insurance",
    "rarity": "uncommon",
    "family": [
      "Ward",
      "Safety"
    ],
    "text": "Clearing a table with 3+ balls left restores 1 ball."
  },
  "chalk_credit": {
    "name": "Pale Chalk",
    "rarity": "uncommon",
    "family": [
      "Ward",
      "Control"
    ],
    "text": "Soft-touch shots that earn Reputation also pay Bankroll."
  },
  "long_glass": {
    "name": "Mourner's Glass",
    "rarity": "uncommon",
    "family": [
      "Omen",
      "Distance"
    ],
    "text": "Long pots add Reputation and Bankroll."
  },
  "hot_hand": {
    "name": "Ember Palm",
    "rarity": "rare",
    "family": [
      "Flame",
      "Chain"
    ],
    "text": "Chain Heat pots earn more Reputation."
  },
  "split_lens": {
    "name": "Mirror Hex",
    "rarity": "rare",
    "family": [
      "Hex",
      "Ricochet"
    ],
    "text": "Ricochet pots add extra Bankroll."
  },
  "called_tab": {
    "name": "Spoken Debt",
    "rarity": "common",
    "family": [
      "Oath",
      "Called"
    ],
    "text": "Called-pocket pots add Bankroll."
  },
  "bumper_policy": {
    "name": "Riot Charm",
    "rarity": "rare",
    "family": [
      "Hex",
      "Chaos"
    ],
    "text": "Cluster-break shots add Reputation and $1 Bankroll."
  },
  "quiet_hands": {
    "name": "Velvet Prayer",
    "rarity": "rare",
    "family": [
      "Ward",
      "Control"
    ],
    "text": "Soft Touch also grants +1 Style."
  },
  "witching_well": {
    "name": "Witching Well",
    "rarity": "uncommon",
    "family": [
      "Field",
      "Control"
    ],
    "text": "A center sigil gently pulls moving object balls inward. Long or carom pots through the well add Reputation."
  },
  "salt_circle": {
    "name": "Salt Circle",
    "rarity": "common",
    "family": [
      "Field",
      "Ward"
    ],
    "text": "A pale ward steadies balls near center. Soft-touch shots gain Reputation and Style."
  },
  "blood_moon": {
    "name": "Blood Moon",
    "rarity": "rare",
    "family": [
      "Field",
      "Risk"
    ],
    "text": "A red moon field wakes risk balls. Risk-ball pots add Reputation and Bankroll."
  },
  "grave_lantern": {
    "name": "Grave Lantern",
    "rarity": "uncommon",
    "family": [
      "Field",
      "Called"
    ],
    "text": "The called pocket burns with a grave light. Called-pocket pots add Reputation and Bankroll."
  }
};
