"""Extract constant Dictionary literals from the Godot scripts into TypeScript data modules.

Run from web/: python3 tools/extract_gd_data.py
Colors become [r, g, b, a] tuples and StringNames become plain strings.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def grab_dict(source: str, const_name: str) -> str:
    start = source.index(f"const {const_name}")
    brace = source.index("{", start)
    depth = 0
    for i in range(brace, len(source)):
        ch = source[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return source[brace : i + 1]
    raise ValueError(const_name)


def gd_to_json(text: str):
    text = re.sub(r"#[^\n\"]*\n", "\n", text)
    text = re.sub(r"Color\(([^)]*)\)", lambda m: "[" + _color(m.group(1)) + "]", text)
    text = re.sub(r"Vector2\(([^)]*)\)", lambda m: "[" + m.group(1) + "]", text)
    text = re.sub(r'&"([^"]*)"', r'"\1"', text)
    text = re.sub(r",(\s*[}\]])", r"\1", text)
    text = text.replace("true", "true").replace("false", "false")
    return json.loads(text)


def _color(args: str) -> str:
    parts = [p.strip() for p in args.split(",")]
    if len(parts) == 3:
        parts.append("1.0")
    return ", ".join(parts)


def emit(name: str, type_name: str, data, out: Path) -> None:
    body = json.dumps(data, indent=2)
    body = re.sub(r"\[\s*([-\d.e,\s]+?)\s*\]", lambda m: "[" + ", ".join(x.strip() for x in m.group(1).split(",")) + "]", body)
    out.write_text(
        "// Generated by tools/extract_gd_data.py from the Godot scripts. Do not edit by hand.\n"
        f"import type {{ {type_name} }} from \"../game/types\";\n\n"
        f"export const {name}: Record<string, {type_name}> = {body};\n"
    )


def main() -> None:
    root_gd = (ROOT / "scripts/GameRoot.gd").read_text()
    relic_gd = (ROOT / "scripts/table/RelicEngine.gd").read_text()
    out_dir = Path(__file__).resolve().parents[1] / "src/data"
    emit("BOARD_DEFS", "BoardDef", gd_to_json(grab_dict(root_gd, "BOARD_DEFS")), out_dir / "boards.ts")
    emit("CUE_DEFS", "CueDef", gd_to_json(grab_dict(root_gd, "CUE_DEFS")), out_dir / "cues.ts")
    emit("CHALK_DEFS", "ChalkDef", gd_to_json(grab_dict(root_gd, "CHALK_DEFS")), out_dir / "chalk.ts")
    emit("RELIC_DEFS", "RelicDef", gd_to_json(grab_dict(relic_gd, "RELICS")), out_dir / "relics.ts")


if __name__ == "__main__":
    main()
